In [1]:
import pandas as pd

In [2]:
data = {
    'roll': [1,2,3,4,5,6,7,8,9,10],
    'marks.s1': [60,40,30,20,50,80,40,30,30,10],
    'marks.s2': [20,30,30,30,50,40,50,60,12,10],
    'marks.s3': [10,40,90,30,40,40,50,60,12,10],
    'results': [0,1,0,1,1,0,0,1,0,1]
}

In [3]:
print(data)

{'roll': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'marks.s1': [60, 40, 30, 20, 50, 80, 40, 30, 30, 10], 'marks.s2': [20, 30, 30, 30, 50, 40, 50, 60, 12, 10], 'marks.s3': [10, 40, 90, 30, 40, 40, 50, 60, 12, 10], 'results': [0, 1, 0, 1, 1, 0, 0, 1, 0, 1]}

In [4]:
studentData = pd.DataFrame(data)
print(studentData)

   roll  marks.s1  marks.s2  marks.s3  results
0     1        60        20        10        0
1     2        40        30        40        1
2     3        30        30        90        0
3     4        20        30        30        1
4     5        50        50        40        1
5     6        80        40        40        0
6     7        40        50        50        0
7     8        30        60        60        1
8     9        30        12        12        0
9    10        10        10        10        1

In [5]:
pd.Series([5,8,7,9,10])

0     5
1     8
2     7
3     9
4    10
dtype: int64

In [6]:
s1 = pd.Series([5,8,7,9,10])

In [7]:
print(s1)

0     5
1     8
2     7
3     9
4    10
dtype: int64

In [9]:
print(s1[0])

5

In [10]:
print(s1[0:3])

0    5
1    8
2    7
dtype: int64

In [11]:
s1 = pd.Series([5,8,7,9,10], index=['a','b','c','d','e'])

In [12]:
s1

a     5
b     8
c     7
d     9
e    10
dtype: int64

In [13]:
s1['a':'d']

a    5
b    8
c    7
d    9
dtype: int64

In [16]:
s2 = pd.Series([80,70,85,65,72], index=['Physics','Chemistry','Mathematics','English','Hindi'])

In [17]:
s2

Physics        80
Chemistry      70
Mathematics    85
English        65
Hindi          72
dtype: int64

In [18]:
s2['Chemistry']

np.int64(70)

In [20]:
s2['Physics':'English']

Physics        80
Chemistry      70
Mathematics    85
English        65
dtype: int64

In [21]:
s2[0]

C:\Users\241b213\AppData\Local\Temp\ipykernel_1820\2344841457.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[0]

np.int64(80)

In [22]:
s2>80

Physics        False
Chemistry      False
Mathematics     True
English        False
Hindi          False
dtype: bool

In [32]:
s2[s2>80]    ## using filter here passing only those values which are satisfying the condition

Physics        84
Mathematics    89
dtype: int64

In [24]:
s2.sum()

np.int64(372)

In [26]:
s2+5 ## broadcast

Physics        85
Chemistry      75
Mathematics    90
English        70
Hindi          77
dtype: int64

In [27]:
s2

Physics        80
Chemistry      70
Mathematics    85
English        65
Hindi          72
dtype: int64

In [31]:
### to store the broadcast 
s2 = s2 + 1
s2

Physics        84
Chemistry      74
Mathematics    89
English        69
Hindi          76
dtype: int64

In [36]:
s2 = pd.DataFrame({'priyanshi': [3,65,27,145,23], 'raghav': [4,2,4,74,74], 'amit':[21,43,65,32,55]}, index=['Physics','Chemistry','Mathematics','English','Hindi'])
print(s2)

             priyanshi  raghav  amit
Physics              3       4    21
Chemistry           65       2    43
Mathematics         27       4    65
English            145      74    32
Hindi               23      74    55

In [37]:
s2['raghav']

Physics         4
Chemistry       2
Mathematics     4
English        74
Hindi          74
Name: raghav, dtype: int64

In [38]:
data1 = pd.read_excel('data2.xlsx')

In [39]:
print(data1.head())

    Age  gender  chest_pain_type  Resting_BP  Cholestrol  Fasting_sugar  \
0  70.0     1.0                4       130.0       322.0            0.0
1  67.0     0.0                3       115.0       564.0            0.0
2  57.0     1.0                2       124.0       261.0            0.0
3  64.0     1.0                4       128.0       263.0            0.0
4  74.0     0.0                2       120.0       269.0            0.0

   Resting_ECG  Max_heart_rate  Exercise_induced_angina  ST_Depression  \
0          2.0           109.0                      0.0            2.4
1          2.0           160.0                      0.0            1.6
2          0.0           141.0                      0.0            0.3
3          0.0           105.0                      1.0            0.2
4          2.0           121.0                      1.0            0.2

   Slope_peak_excercise  No_of_major_vessels  Thal  Disease
0                   2.0                  3.0   3.0      2.0
1                   2.0                  0.0   7.0      1.0
2                   1.0                  0.0   7.0      2.0
3                   2.0                  1.0   7.0      1.0
4                   1.0                  1.0   3.0      1.0

In [40]:
data1.head(10)

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
5,65.0,1.0,4,120.0,177.0,0.0,0.0,140.0,0.0,0.4,1.0,0.0,7.0,1.0
6,56.0,1.0,3,NaN,256.0,1.0,2.0,142.0,1.0,0.6,2.0,1.0,6.0,2.0
7,59.0,1.0,4,110.0,239.0,0.0,2.0,142.0,1.0,1.2,2.0,1.0,7.0,2.0
8,60.0,1.0,4,NaN,293.0,0.0,2.0,170.0,0.0,1.2,2.0,2.0,7.0,2.0
9,63.0,0.0,4,150.0,407.0,0.0,2.0,154.0,0.0,4.0,2.0,3.0,7.0,2.0

In [41]:
data1.tail()

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [42]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      267 non-null    float64
 1   gender                   268 non-null    float64
 2   chest_pain_type          270 non-null    int64
 3   Resting_BP               266 non-null    float64
 4   Cholestrol               267 non-null    float64
 5   Fasting_sugar            266 non-null    float64
 6   Resting_ECG              265 non-null    float64
 7   Max_heart_rate           266 non-null    float64
 8   Exercise_induced_angina  267 non-null    float64
 9   ST_Depression            265 non-null    float64
 10  Slope_peak_excercise     266 non-null    float64
 11  No_of_major_vessels      264 non-null    float64
 12  Thal                     262 non-null    float64
 13  Disease                  264 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 29.7 KB

In [43]:
data1.shape

(270, 14)

In [44]:
data1 = data1.drop_duplicates()

In [45]:
data1.columns

Index(['Age', 'gender', 'chest_pain_type', 'Resting_BP', 'Cholestrol',
       'Fasting_sugar', 'Resting_ECG', 'Max_heart_rate',
       'Exercise_induced_angina', 'ST_Depression', 'Slope_peak_excercise',
       'No_of_major_vessels', 'Thal', 'Disease'],
      dtype='object')

In [46]:
data1[['Age']]

      Age
0    70.0
1    67.0
2    57.0
3    64.0
4    74.0
..    ...
265  52.0
266  44.0
267  56.0
268  57.0
269  67.0

[267 rows x 1 columns]

In [48]:
data1.rename(columns={'Age': 'ages', 'gender':'Genders'})

,ages,Genders,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [49]:
data1.dropna()

,Age,gender,chest_pain_type,Resting_BP,Cholestrol,Fasting_sugar,Resting_ECG,Max_heart_rate,Exercise_induced_angina,ST_Depression,Slope_peak_excercise,No_of_major_vessels,Thal,Disease
0,70.0,1.0,4,130.0,322.0,0.0,2.0,109.0,0.0,2.4,2.0,3.0,3.0,2.0
1,67.0,0.0,3,115.0,564.0,0.0,2.0,160.0,0.0,1.6,2.0,0.0,7.0,1.0
2,57.0,1.0,2,124.0,261.0,0.0,0.0,141.0,0.0,0.3,1.0,0.0,7.0,2.0
3,64.0,1.0,4,128.0,263.0,0.0,0.0,105.0,1.0,0.2,2.0,1.0,7.0,1.0
4,74.0,0.0,2,120.0,269.0,0.0,2.0,121.0,1.0,0.2,1.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52.0,1.0,3,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,1.0
266,44.0,1.0,2,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,1.0
267,56.0,0.0,2,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,1.0
268,57.0,1.0,4,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,1.0
269,67.0,1.0,4,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0

In [50]:
z = data1['Age']
z.head()

0    70.0
1    67.0
2    57.0
3    64.0
4    74.0
Name: Age, dtype: float64

In [52]:
mean = z.mean()
print(mean)

54.53030303030303